name: Yasca PR

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PIP Dependencies
        run: pip install -r requirements_dev.txt

      - name: Flake8 styles
        run: python -m flake8 ./yasca

      - name: Bandit security scan
        run: python -m bandit -r ./yasca

      - name: Safety dependency scan
        run: python -m safety check

      - name: Checkout origin branch if PR 'to-branch' is main
        if: github.base_ref == 'main'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: BumpVersion if PR 'to-branch' is main
        if: github.base_ref == 'main'
        run: |
          bump2version minor

      - name: Commit back to the repo
        if: github.base_ref == 'main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumpversion changes